version: '3'
services:
  db:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: "test"
    container_name: db_mysql
  redis:
    image: redis:latest
    container_name: db_redis
